{% set name = "napari" %}
{% set version = "REPLACE_ME" %}  # replaced dynamically by the CI
{% set build = 0 %}

package:
  name: napari-meta

source:
  # This section has been patched from the original conda-forge feedstock
  # so it uses the mounted volume of the cloned repo in a Docker image
  path: /home/conda/feedstock_root/napari-source

build:
  number: {{ build }}

outputs:
  - name: napari-base
    version: {{ version }}
    build:
      noarch: python
      script: PIP_NO_INDEX=True PIP_NO_DEPENDENCIES=True PIP_NO_BUILD_ISOLATION=False PIP_IGNORE_INSTALLED=True PYTHONDONTWRITEBYTECODE=True {{ PREFIX }}/bin/python -m pip install . -vv
      entry_points:
        - napari = napari.__main__:main

    requirements:
      host:
        - python >=3.10
        - pip
        - setuptools >=69
        - setuptools_scm >=8
      run:
        - python >=3.10

        # dependencies matched to pyproject.toml
        - app-model >=0.3.0,<0.4.0a
        - appdirs >=1.4.4
        - cachey >=0.2.1
        - certifi >=2018.1.18
        # Do not depend on base "dask" package since it pulls
        # in the distributed dependency
        # conda-forge doesn't have the dask-array subpackage
        # so depend on cytoolz and numpy manually
        - dask-core >=2021.10.0
        - cytoolz >=0.11.0
        - imageio >=2.20,!=2.22.1
        - jsonschema >=3.2.0
        - lazy_loader >=0.2
        - magicgui >=0.7.0
        - napari-console >=0.1.1
        - napari-plugin-engine >=0.1.9
        - npe2 >=0.7.8
        - numpy >=1.24.2
        - numpydoc >=1.0.0
        - pandas >=1.3.3
        - pillow >=9.0
        - pint >=0.17
        - psutil >=5.9.0
        - psygnal >=0.5.0
        - pydantic >=2.2.0
        - pygments >=2.6.0
        - pyopengl >=3.1.5
        - pywin32  # this is Windows only, but the package is no-op on Unix
        - pyyaml >=6.0
        - qtpy >=1.10.0
        - scikit-image >=0.19.1
        - scipy >=1.10.1
        - superqt >=0.6.7
        - tifffile >=2022.4.8
        - toolz >=0.11.0
        - tqdm >=4.56.0
        - typing_extensions >=4.6.1
        - vispy >=0.14.1,<0.15.0a0
        - wrapt >=1.13.3

      run_constrained:
        - pyside2 >=5.15.1
        - pyside6 <6.5|>=6.7
        - pyqt >=5.15.8,<6.0a0|>=6.5,!=6.6.1

    test:
      requires:
        - pyqt
        - pip
      # needed if pytest is uncommented below in 'commands'
      #   - hypothesis
      #   - pytest
      #   - pytest-faulthandler
      #   - pytest-qt
      #   - xarray
      #   - pandas
      #   - pytest-timeout
      imports:
        - napari
      commands:
        - setx QT_API "pyqt5"  # [win]
        - export QT_API=pyqt5  # [unix]
        - which napari
        - napari --info  # [not linux]
        - 'QT_DEBUG_PLUGINS=1 LIBGL_DEBUG=verbose xvfb-run --auto-servernum napari --info | grep -C99 "napari: ${PKG_VERSION}"'  # [linux]
        # - pytest --pyargs napari

    about:
      home: http://napari.org
      license: BSD-3-Clause AND MIT
      license_file:
        - LICENSE
        - napari/_vendor/darkdetect/LICENSE
        - napari/_vendor/qt_json_builder/LICENSE
      summary: a fast n-dimensional image viewer in Python, with only the required dependencies
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

  - name: napari
    version: {{ version }}
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('napari-base', exact=True) }}
        - fsspec
        - napari-plugin-manager >=0.1.3,<0.2.0a0
        - napari-svg >=0.1.8
        - numba >=0.57.1
        - pooch >=1.3.0
        # - py-triangle  # can segfault with bad data: https://github.com/napari/napari/pull/6654
        - zarr >=2.12.0
    test:  # just to check that the environment can indeed solve
      requires:
        - pyside2  # use this opportunity to test solvability with other backend
      imports:
        - napari
    about:
      home: http://napari.org
      license: BSD-3-Clause AND MIT
      license_file: LICENSE
      summary: a fast n-dimensional image viewer in Python
      description: a fast n-dimensional image viewer in Python
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

  - name: napari-menu
    version: {{ version }}
    build:
      noarch: python
      script:
        - mkdir -p "${PREFIX}/Menu"
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ SRC_DIR }}/resources/conda_menu_config.json" > "{{ PREFIX }}/Menu/napari-menu.json"
        - cp "{{ SRC_DIR }}/napari/resources/logo.png" "{{ PREFIX }}/Menu/napari.png"
        - cp "{{ SRC_DIR }}/napari/resources/icon.icns" "{{ PREFIX }}/Menu/napari.icns"
        - cp "{{ SRC_DIR }}/napari/resources/icon.ico" "{{ PREFIX }}/Menu/napari.ico"
    requirements:
      build:
        - sed     # [unix]
      run:
        - napari {{ version }}.*
    test:
      imports:
        - napari
      commands:
        - test -f ${CONDA_PREFIX}/Menu/napari-menu.json

    # app:
    #   entry: python -m napari
    #   icon: "{{ SRC_DIR|replace('\\', '/') }}/napari/resources/logo.png"
    #   summary: a fast n-dimensional image viewer in Python
    #   own_environment: True

    about:
      home: http://napari.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: provides menu icons for napari
      description: provides menu icons for napari
      doc_url: http://napari.org
      dev_url: https://github.com/napari/napari

about:
  home: http://napari.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a fast n-dimensional image viewer in Python
  description: a fast n-dimensional image viewer in Python
  doc_url: http://napari.org
  dev_url: https://github.com/napari/napari

extra:
  feedstock-name: napari
  recipe-maintainers:
    - jni
    - sofroniewn
    - kne42
    - royerloic
    - AhmetCanSolak
    - tlambert03
    - goanpeca
    - jaimergp
